"""
to identify the deployment in our k8s cluster
"""
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-postgres-pvc
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: django-postgres
spec:
  selector:
    matchLabels:
      app: django
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
      app: django
      tier: postgres
  volumes:
    - name:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: postgres
    spec:
      containers:
        - image: postgres:12
          name: postgres
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: djangodb
            - name: POSTGRES_USER
              value: djagouser
            - name: POSTGRES_PASSWORD
              valueForm:
                secretKeyref:
                  name: db-password
                  key: password

